CREATE TABLE SERVICE_CENTER(SID char(5) PRIMARY KEY, NAME varchar(50), PHONE char(11), ADDRESS varchar(50), CONSTRAINT CHK_PHONE_SERVICE_CENTER CHECK(REGEXP_LIKE(PHONE, '[0-9]{11}')));

CREATE TABLE MONTHLY(EMPID char(9) PRIMARY KEY, NAME varchar(50), PHONE char(10), POSITION varchar(20), ADDRESS varchar(50), SID char(5), START_DATE date, SALARY float, EMAIL varchar(50), CONSTRAINT FK_MONTHLY FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID), CONSTRAINT CHK_POSITION_MONTHLY CHECK(POSITION IN ('manager','receptionist')), CONSTRAINT CHK_PHONE_MONTHLY CHECK(REGEXP_LIKE(PHONE, '[0-9]{10}')));

CREATE TABLE HOURLY(EMPID char(9) PRIMARY KEY, NAME varchar(50), PHONE char(10), POSITION varchar(20) CONSTRAINT CHK_POSITION_HOURLY CHECK(POSITION IN ('mechanic')), ADDRESS varchar(50), SID char(5), START_DATE date, WAGE float, EMAIL varchar(50), CONSTRAINT FK_HOURLY FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID), CONSTRAINT CHK_PHONE_HOURLY CHECK(REGEXP_LIKE(PHONE, '[0-9]{10}')));

CREATE TABLE CUSTOMER(CUSID char(4) UNIQUE, NAME varchar(50), EMAIL varchar(50) PRIMARY KEY, PHONE char(10), ADDRESS varchar(50), SID char(5), CONSTRAINT FK_CUSTOMER FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID), CONSTRAINT CHK_PHONE_CUSTOMER CHECK(REGEXP_LIKE(PHONE, '[0-9]{10}')));

CREATE TABLE MAKE(MAKE_NAME varchar(25) PRIMARY KEY);

CREATE TABLE MODEL(MODEL varchar(10), MAKE_NAME varchar(25), PRIMARY KEY(MODEL,MAKE_NAME), CONSTRAINT FK_MODEL FOREIGN KEY(MAKE_NAME) REFERENCES MAKE(MAKE_NAME));

CREATE TABLE CAR(LICENSE_PLATE varchar(10) PRIMARY KEY, MAKE_NAME varchar(25), MODEL varchar(10), YEAR number(4), PURCHASE_DATE date, CURRENT_MILEAGE int, LAST_SERVICE_DATE date, CUSID char(4), CONSTRAINT FK1_CAR FOREIGN KEY(CUSID) REFERENCES CUSTOMER(CUSID), CONSTRAINT FK2_CAR FOREIGN KEY(MODEL,MAKE_NAME) REFERENCES MODEL(MODEL,MAKE_NAME));

CREATE TABLE PART_TYPE(PARTID CHAR(5) PRIMARY KEY, MAKE_NAME varchar(25), NAME varchar(50), WARRANTY int, PRICE float, CONSTRAINT FK_PART_TYPE FOREIGN KEY(MAKE_NAME) REFERENCES MAKE(MAKE_NAME));

CREATE TABLE PART_ORDER(ORDERID char(5) PRIMARY KEY, PARTID char(5), PLACED_BY char(5), STATUS varchar(50), QUANTITY int, PO_DATE date, CONSTRAINT FK_PART_ORDER FOREIGN KEY(PLACED_BY) REFERENCES SERVICE_CENTER(SID));

CREATE TABLE DISTRIBUTOR(DISTID char(5) PRIMARY KEY, NAME char(2));

CREATE TABLE WINDOWS(PARTID char(5), DISTID char(5), DELIVERY_WINDOW int, CONSTRAINT FK1_WINDOWS FOREIGN KEY(PARTID) REFERENCES PART_TYPE(PARTID), CONSTRAINT FK2_WINDOWS FOREIGN KEY(DISTID) REFERENCES DISTRIBUTOR(DISTID), PRIMARY KEY(PARTID,DISTID));

CREATE TABLE REQUEST(REQID char(5) PRIMARY KEY, REQ_DATE timestamp, SID char(5), MILEAGE int, LICENSE_PLATE varchar(10), CUSID char(4), EMPID char(9), DURATION int, CONSTRAINT FK1_REQUEST FOREIGN KEY(EMPID) REFERENCES HOURLY(EMPID), CONSTRAINT FK2_REQUEST FOREIGN KEY(LICENSE_PLATE) REFERENCES CAR(LICENSE_PLATE), CONSTRAINT FK3_REQUEST FOREIGN KEY(CUSID) REFERENCES CUSTOMER(CUSID), CONSTRAINT FK4_REQUEST FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID));

CREATE TABLE MAINTENANCE_SERVICE(REQID char(5) PRIMARY KEY, CATEGORYNAME char(1), CONSTRAINT FK_MAINTENANCE_SERVICE FOREIGN KEY(REQID) REFERENCES REQUEST(REQID));

CREATE TABLE CAR_SPECS(CATEGORY_NAME char(1), MAKE_NAME varchar(25), MODEL varchar(10), MILES float, YEAR int, MONTH int, PRIMARY KEY(CATEGORY_NAME,MAKE_NAME,MODEL), CONSTRAINT FK_CAR_SPECS FOREIGN KEY(MAKE_NAME) REFERENCES MAKE(MAKE_NAME));

CREATE TABLE RATE(RATE_TYPE varchar(4) PRIMARY KEY, AMOUNT float);

CREATE TABLE BASIC_SERVICE(BASIC_SERVICE_ID char(5) PRIMARY KEY, ESTIMATED_TIME float, B_NAME varchar(100), RATE_TYPE varchar(4) CONSTRAINT CHK_RATE_TYPE CHECK(RATE_TYPE IN ('high','low')), CONSTRAINT FK_BASIC_SERVICE FOREIGN KEY(RATE_TYPE) REFERENCES RATE(RATE_TYPE));

CREATE TABLE LOGIN(USERNAME varchar(50), PASSWORD varchar(50), ROLE varchar(12) CONSTRAINT CHK_ROLE CHECK(ROLE IN ('manager','receptionist','customer')));

CREATE TABLE INVENTORY(PARTID char(5), SID char(5), QUANTITY int, MIN_QUANTITY int, MIN_ORDER int, PRIMARY KEY(PARTID, SID), CONSTRAINT FK1_INVENTORY FOREIGN KEY(PARTID) REFERENCES PART_TYPE(PARTID), CONSTRAINT FK2_INVENTORY FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID));

CREATE TABLE FROM_DIST(ORDERID char(5), DISTID char(5), PARTID char(5), PRIMARY KEY(ORDERID, DISTID,PARTID), CONSTRAINT FK1_FROM_DIST FOREIGN KEY(ORDERID) REFERENCES PART_ORDER(ORDERID), CONSTRAINT FK2_FROM_DIST FOREIGN KEY(DISTID,PARTID) REFERENCES WINDOWS(DISTID,PARTID));

CREATE TABLE FROM_SERVICE_CENTER(ORDERID char(5), SID char(5),WINDOW int DEFAULT 1, PRIMARY KEY(ORDERID, SID), CONSTRAINT FK1_FROM_SERVICE_CENTER FOREIGN KEY(ORDERID) REFERENCES PART_ORDER(ORDERID), CONSTRAINT FK2_FROM_SERVICE_CENTER FOREIGN KEY(SID) REFERENCES SERVICE_CENTER(SID));

CREATE TABLE COMPOSED_OF(CATEGORY_NAME char(1),MAKE_NAME varchar(25), MODEL varchar(10), BASIC_SERVICE_ID char(5), PRIMARY KEY(CATEGORY_NAME, MODEL, MAKE_NAME ,BASIC_SERVICE_ID), CONSTRAINT FK1_COMPOSED_OF FOREIGN KEY(CATEGORY_NAME, MODEL,MAKE_NAME) REFERENCES CAR_SPECS(CATEGORY_NAME, MODEL,MAKE_NAME), CONSTRAINT FK2_COMPOSED_OF FOREIGN KEY(BASIC_SERVICE_ID) REFERENCES BASIC_SERVICE(BASIC_SERVICE_ID));

CREATE TABLE USES(BASIC_SERVICE_ID char(5),PARTID char(5),PRIMARY KEY(BASIC_SERVICE_ID,PARTID), CONSTRAINT FK1_USES FOREIGN KEY(BASIC_SERVICE_ID) REFERENCES BASIC_SERVICE(BASIC_SERVICE_ID), CONSTRAINT FK2_USES FOREIGN KEY(PARTID) REFERENCES PART_TYPE(PARTID));

CREATE TABLE CONTAINS(PARTID char(5), MAKE_NAME varchar(25), MODEL varchar(10), COUNT int, PRIMARY KEY(PARTID,MAKE_NAME,MODEL), CONSTRAINT FK1_CONTAINS FOREIGN KEY(PARTID) REFERENCES PART_TYPE(PARTID), CONSTRAINT FK2_CONTAINS FOREIGN KEY(MODEL,MAKE_NAME) REFERENCES MODEL(MODEL,MAKE_NAME));

CREATE TABLE REPAIR_NAME(R_NAME varchar(50) PRIMARY KEY, DIAGNOSTICS varchar(100), D_FEE int);

CREATE TABLE REPAIR_SERVICE(REQID char(5),R_NAME varchar(50), CONSTRAINT FK1_REPAIR_SERVICE FOREIGN KEY(REQID) REFERENCES REQUEST(REQID), CONSTRAINT FK2_REPAIR_SERVICE FOREIGN KEY(R_NAME) REFERENCES REPAIR_NAME(R_NAME), PRIMARY KEY(REQID, R_NAME));







CREATE TABLE REPAIR(R_NAME varchar(50), BASIC_SERVICE_ID char(5), CONSTRAINT FK1_REPAIR FOREIGN KEY(R_NAME) REFERENCES REPAIR_NAME(R_NAME), CONSTRAINT FK2_REPAIR FOREIGN KEY(BASIC_SERVICE_ID) REFERENCES BASIC_SERVICE(BASIC_SERVICE_ID), PRIMARY KEY(R_NAME, BASIC_SERVICE_ID));

























