CREATE OR REPLACE Function AUTHENTICATE
   (UNAME IN LOGIN.USERNAME%type, PWD IN LOGIN.PASSWORD%type)
   RETURN LOGIN.ROLE%type
IS
   R LOGIN.ROLE%type;

   CURSOR c1
   IS
     SELECT L.ROLE FROM LOGIN L WHERE L.USERNAME = UNAME AND L.PASSWORD = PWD;

BEGIN

   OPEN c1;
   FETCH c1 INTO R;

   if c1%notfound then
      R := 'Not Found';
   end if;

   CLOSE c1;

RETURN R;

END;
/




CREATE OR REPLACE PROCEDURE 
	CHECK_FOR_RECEPTIONIST(SERVICECENTERID IN char,C OUT NUMBER) 
IS 
BEGIN 
	SELECT COUNT(M.POSITION) INTO C FROM MONTHLY M WHERE M.POSITION='receptionist' AND M.SID=SERVICECENTERID;
	COMMIT;
END;
/





